name: 'desafio_data_eng'
version: 1.0.2 # Versão do Projeto
config-version: 2  # Versão da Configuração

profile: local_profile

model-paths: ["models"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Estrutura dos Modelos
models:
  desafio_data_eng:
    staging:
      +database: "{{ var('database') }}"
      materialized: table
    marts:
      materialized: table

# Optional: Specify seeds, snapshots, etc.
seeds:
  desafio_data_eng:
    enabled: true