name: desafio_data_eng

version: 1.0.0
profile: local_profile

# This specifies where DBT will look for models
model-paths: ["models"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Define the models structure
models:
  desafio_data_eng:
    staging:
      materialized: view
    marts:
      materialized: table

# Optional: Specify seeds, snapshots, etc.
seeds:
  desafio_data_eng:
    enabled: true