local_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: userrio
      password: hunter2 # @TODO secret
      port: 5432
      dbname: adm_terceirizados_fed
      schema: dbt_schema
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1