version: '3.8'

services:
  prefect-server:
    image: prefecthq/server:core-0.15.9
    ports:
      - "4200:4200"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./.env:/prefect-server/.env
    environment:
      PREFECT_SERVER__DB__CONNECTION_URL: "postgresql://postgres:postgres@postgres:5432/cgu_terceirizados"
    command: prefect server start

  # prefect-agent:
  #   image: prefecthq/prefect:core-0.15.9
  #   environment:
  #     PREFECT__CLOUD__AGENT__AUTH_TOKEN: ${PREFECT_AGENT_TOKEN}
  #   command: prefect agent local start --label default

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # @TODO secret
      POSTGRES_DB: cgu_terceirizados

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"