
version: 2

models:
  - name: adm_terceirizados_fed_staging_new_columns
    description: "Dados de pessoal terceirizado de órgãos do Poder Executivo Federal, incluindo autarquias e fundações públicas, no padrão de estilo do Escritório de Dados"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null