name: staging
version: 2

models:
  - name: raw
    description: "Dados Abertos de Terceirizados de Órgãos Federais Crus"

  - name: cleaned
    description: "Dados Abertos de Terceirizados de Órgãos Federais com NULL padrão"
    columns:
      - name: id_terc
        description: "ID do Terceirizado"
        tests:
          - unique
          - not_null
    depends_on:
      - ref('raw')

  - name: transformed
    description: "Dados Abertos de Terceirizados de Órgãos Federais com tipos de colunas definidos"
    columns:
      - name: id_contratado
        description: "ID do Terceirizado Federal Contratado"
        tests:
          - unique
          - not_null
    depends_on:
      - ref('cleaned')

